
require 'flex-config.amenity'
require 'flex-config.building'
require 'flex-config.indoor'
require 'flex-config.infrastructure'
require 'flex-config.landuse'
require 'flex-config.leisure'
require 'flex-config.natural'
require 'flex-config.place'
require 'flex-config.poi'
require 'flex-config.public_transport'
require 'flex-config.road'
require 'flex-config.shop'
require 'flex-config.tags'
require 'flex-config.traffic'
require 'flex-config.water'
